spring:
  datasource:
    hikari:
      source-database:
        jdbc-url: jdbc:postgresql://${SOURCE_DB_DOMAIN}:${SOURCE_DB_PORT}/${SOURCE_DB_NAME}
        username: ${SOURCE_DB_USER}
        password: ${SOURCE_DB_PASSWORD}
        driver-class-name: org.postgresql.Driver

      target-database:
        jdbc-url: jdbc:postgresql://${TARGET_DB_DOMAIN}:${TARGET_DB_PORT}/${TARGET_DB_NAME}
        username: ${TARGET_DB_USER}
        password: ${TARGET_DB_PASSWORD}
        driver-class-name: org.postgresql.Driver


  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
